name: flutter_pushy_example
description: Demonstrates how to use the flutter_pushy plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pushy:
    path: ../
  
flutter:
  uses-material-design: true